# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wonicon的日常灌水
email: conciselove@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    Powered by Jekyll with default theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wonicon.com" # the base hostname & protocol for your site
github_username: Wonicon

# Build settings
# Use redcarpet instead of the default kramdown
# to support fency code block
markdown: redcarpet

permalink: /:title.html
